#!/usr/bin/python
import os
import sys
import time
import display
import display_buffer
import smallfonts
import pygame

import buttons

but = buttons.Buttons(hw=False, stdin=True, pygame=True)

scale=3
width=128
height=64

#info = pygame.display.Info()

#print pygame.display.Info()
#print size
#screen = pygame.display.set_mode(size, pygame.FULLSCREEN)

buffer = display_buffer.DisplayBuffer(width, height)
display = display.Display(buffer, spi=False, virtual=True)
try:
    display.init()
except IOError:
    print "SPI interface disabled"

for x in range(2):
    buffer.draw_string(0, x*22, "1BRMLAB7nryYgFGrG8x9S", smallfonts.Font5x8)
    buffer.draw_string(0, x*22+10, "\x80 12381.87431928", smallfonts.Font7x8)
    buffer.invert(0, x*22+9, width-1, x*22+17)

# Status line
buffer.frame(0, height-20, width-1, height-20)
buffer.draw_string(0, height-18, "Are you sure?", smallfonts.Font5x8)

# Left button title
buffer.draw_string(6, height-9, "Cancel", smallfonts.Font5x8)
buffer.invert(0, height-10, 45, height-1)

# Right button title
buffer.draw_string(width-44, height-9, "Confirm", smallfonts.Font5x8)
buffer.invert(width-46, height-10, width-1, height-1)

while True:
    but.read()
    display.refresh()
    time.sleep(0.1)
    

#raw_input()

'''
while True:
    b = bitkey.buttonsRead()
    if b[0]:
        bitkey.oledInvert(82, 54, 126, 62)
        bitkey.oledRefresh()
    if b[1]:
        bitkey.oledInvert(1, 54, 45, 62)
        bitkey.oledRefresh()
    print 'yes:', b[1], 'no:', b[0]
    time.sleep(0.1)
'''
